### ISSUE TITLE
C#版本的 生成工具在哪里!

### ISSUE THREAD

**Issue by xjaksyt2008** [TarsCloud/TarsTup#5]
C#版本的 生成工具在哪里!

**Comment by ETZhangSX** [comment]
工具源码在`TarsCloud/TarsCpp/tools/tars2cs/`中，将源码编译后即可获得生成工具，通过以下命令编译安装TarsCpp开发框架
```sh
git clone https://github.com/TarsCloud/TarsCpp.git --recursive
cd TarsCpp
cmake .
make
make install
```
`/usr/local/tars/cpp/tools/tars2cs`即为C#代码生成脚本

**Comment by xjaksyt2008** [comment]
谢谢,知道了

**Comment by xjaksyt2008** [comment]
--with-servant 参数 没有作用 是没有写功能吗

**Comment by ETZhangSX** [comment]
目前的确没有`--with-servant`参数的实现
